### ISSUE TITLE
Error when editing a date

### ISSUE THREAD

**Issue by btsvennes** [tpeczek/Lib.Web.Mvc#100]
Hi!

First of all, thank you for a great library.

I've encountered an error when trying to edit a DateTime-cell. I seems like your code tries to access $.jgrid.formatter.date.dayNames, but this doesn't exist. The dayNames are located in $.jgrid.locals.<culture>.formatter.date.dayNames and at this point at least doesn't seem to have extended the $.jqgrid.formatter.

I'm using v6.8 of Lib.Web.Mvc and 4.14.0-pre of "free jqGrid".

Regards,
Bjørn Terje Svennes

**Comment by btsvennes** [comment]
I changed $.jgrid.formatter.date.dayNames to $.jgrid.locales[$.jgrid.defaults.locale].formatter.date.dayNames for testing (file JqGridColumnElementOptions.cs), and it worked. But there has to be a better way for retrieving the formatter from jqGrid. The same issue exists for monthNames.

**Comment by tpeczek** [comment]
Thank you for reporting, I will look into this.

**Comment by tpeczek** [comment]
So it seams that `$.jgrid.formatter.date.dayNames` has been removed after version 4.7. What is worst there are different changes depending and which jqGrid version is being used.

For Guriddo jqGrid the way to go seems to be `$.jgrid.getRegional` method:

`$.jgrid.getRegional($('#gridId')[0], 'formatter.date.dayNames')`

While in free jqGrid a `getGridRes` method has been added.

`$('#gridId').jqGrid('getGridRes', 'formatter.date.dayNames')`

So this will be first "branch" in helper code.

**Comment by btsvennes** [comment]
So the two projects are now going its separate ways it seems? A strange way of solving the issue with locales. Would make much more sense if they kept it the way it was, something that is more in line with how other libraries handle locales.

Anyway, thank you for solving this so quickly.

**Comment by tpeczek** [comment]
Well this is not solved yet. I would say about a week until I push the code and about two weeks till release.

**Comment by tpeczek** [comment]
@btsvennes  Can you pull the latest code and double check the fix (you will need to set CompatibilityMode accordingly)?

**Comment by btsvennes** [comment]
It works great! I can edit DateTime-properties using jQuery UI as before. Thanks!
