### ISSUE TITLE
Range Request in ASP.NET MVC - Failed to play with Google browser and Opera

### ISSUE THREAD

**Issue by matmiranda** [tpeczek/Lib.Web.Mvc#102]
I'm facing the problem with Google browser and Opera.

Please check link in stackoverflow: http://stackoverflow.com/questions/43285298/range-request-in-asp-net-mvc-failed-to-play-with-google-browser-and-opera

Any Solution ?

**Comment by tpeczek** [comment]
As this seems to be a question only there is no need for issue. I've responded to the SO question and we will do any follow up there. I'm closing this issue, if something pops up which indeed should require a fix a new issue will be opened.
