### ISSUE TITLE
MINOR: Not possible to format error messages for delete action

### ISSUE THREAD

**Issue by btsvennes** [tpeczek/Lib.Web.Mvc#103]
Hi.

This is a minor error, but would be nice to have this feature. As I understand the jqGrid-library has an option for formating the error message on add, edit delete action. In Lib.Web.Mvc this is only supported for add and edit (through the JqGridNavigatorEditActionOptions-attribute), but not for delete (which use the JqGridNavigatorDeleteActionOptions-attribute). Is there a reason for this?

Regards,
Bjørn Terje Svennes

**Comment by tpeczek** [comment]
You are refereeing to JqGridNavigatorEditActionOptions.ErrorTextFormat property right?

**Comment by btsvennes** [comment]
That is correct. According to for instance http://www.guriddo.net/demo/guriddojs/ (Edit form with custom template), the errorTextFormat-option is also available for the delete dialog.

**Comment by tpeczek** [comment]
Yes, it seems like indeed it should be moved to the base and shared by both. I'll assign this to a patch release. It is scheduled for end of month right now, but might get pushed.
