### ISSUE TITLE
Compatibility with free-jqgrid or Guriddo

### ISSUE THREAD

**Issue by mfsbo** [tpeczek/Lib.Web.Mvc#112]
Does this now support free-jqgrid version or just the non-commercial version of Guriddo.
I was looking at Bootstrap4 support and there seem to be 2 different options.
[One Defines UI](http://www.guriddo.net/demo/bootstrap/functionality/bootstrap4/) as 
`$.jgrid.defaults.styleUI = 'Bootstrap4';`
The [Other one](https://free-jqgrid.github.io/getting-started/index.html) defined it as `guiStyle` as you can see in this [example Fiddle](https://jsfiddle.net/OlegKi/07ousnfk/):
`guiStyle: "bootstrap4",`

Lib.Web.MVC only offers StyleUI option when initializing and so I assume it only supports the guriddo.net commercial version and not the free version.

**Comment by tpeczek** [comment]
Hi,


There is no explicit support for Guriddo jqGrid and free jqGrid. At least not in a similar way as the ASP.NET Core successor of this library ([Lib.AspNetCore.Mvc.JqGrid](https://github.com/tpeczek/Lib.AspNetCore.Mvc.JqGrid)) has.

All the functionalities that were supported at the moment of split (jqGrid 4.7.0) should work. Anything added later depends on contributor.

In general this project is in semi-maintenance mode. I'm still fixing bugs, I'm happy to take contributions and I will add new features if sponsored. But my main effort is around my active ASP.NET Core projects.
