### ISSUE TITLE
[Work Item #13273] RangeFileStreamResult not working for ios and android

### ISSUE THREAD

**Issue by tpeczek** [tpeczek/Lib.Web.Mvc#90]
<b>Reported at CodePlex by abdelkader27 on 2014-08-13 15:28:36 (UTC)</b>

Hi,

I want to thank your for your great work.

I use RangeFileStreamResult for reading a video, the video is playing correctly on desktop but on Android and IOS devices it's a black screen, when I click on the play button there's nothing.

Can you help me?

<hr />

<b>Closed at CodePlex by TPeczek on 2014-09-03 16:55:40 (UTC) - Wont Fix</b>

Seems like an issue with IIS and specific mobile platforms.

**Comment by UweKeim** [comment]
There is also a chance that [dynamic/static compression is activated in IIS](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/urlcompression).

One can try:

    <urlCompression doStaticCompression="false" doDynamicCompression="false" />

And see whether any improvement is visible.
