### ISSUE TITLE
Decoupling 

### ISSUE THREAD

**Issue by Defee** [tpeczek/Lib.Web.Mvc#95]
Can i ask you to decouple your solution? I have a separated View Model assembly so it is not that good to plug all module to it, but i want to use Jq Attributes there, for using Vns with jqGrid in my views. I can help with it if you need it.

**Comment by tpeczek** [comment]
I'm afraid there might be no possibility of decoupling this in a way which would satisfy your needs. All the attributes rely on `IMetadataAware` interface which brings dependency on System.Web.Mvc - I'm guessing this is the one you would like to avoid. In order to avoid usage of `IMetadataAware` interface the core part of library would have to start using reflection and this is not a path I would like to go.

**Comment by Defee** [comment]
I've made some investigations. You can actually do some decoupling . I suggest to divide process into parts:
1) Module decoupling see the diagram. It will help with a support and ordering of logical data|buisness parts
![dependencies graph](https://cloud.githubusercontent.com/assets/8367665/10599673/e9a68638-770c-11e5-858f-9fa4a59aaf97.png)
- You have all logically independent modules in one assembly, it's not that great. So I suggest to split it into three assemblies: 
1. Lib.Web.Mvc.Core 
2. Lib.Web.Mvc.JqGrid 
3. Lib.Web.Mvc,TreeView

2) Refactor the class libraries. A class behaviour can be moved  to special assemblies. One will have interfaces for interaction with the classes, that should have a behaviour and the other will have implementations. So you would separate the classes and the business logic of your JqGrid Wrapper.

3) Do more improvements with a fresh look

**Comment by tpeczek** [comment]
I never said that decoupling is not possible, I've just assumed (apparently incorrectly) that your goal is to remove unnecessary additional references from your View Model assembly. The changes you propose above doesn't provide ay gains for your scenario.

Now if it comes to decoupling as a general idea it all depends how you look at it.

Currently Lib.Web.Mvc lives in pre ASP.NET 5 word where such a logical organization was typical (you should look at this library as something corresponding to System.Web.Mvc in its organization).

ASP.NET 5 brings strong decoupling to the table as a general industrial trend but still some love it and some hate it (some event starts talking about "NuGet Dependency Hell").

In general as long as this library stays in pre ASP.NET 5 (which is probably not for long) this might be not needed effort. When time comes to migrate this to ASP.NET 5 this probably will be one of changes done as part of the process.

**Comment by tpeczek** [comment]
There will be no change for ASP.NET MVC version.

The ASP.NET Core MVC [version](https://github.com/tpeczek/Lib.AspNetCore.Mvc.JqGrid) has been decoupled.
