### ISSUE TITLE
Version for ASP.NET Core MVC

### ISSUE THREAD

**Issue by jlusarreta** [tpeczek/Lib.Web.Mvc#97]
Are you planing a new version for Asp.Net 5 ? (or 1 core...)

**Comment by tpeczek** [comment]
Yes, the work is already in progres with initial goal of releasing some alphas in March. The library will also be cut into couple smaller, independent ones.

**Comment by jlusarreta** [comment]
How can I collaborate?
I started a new project ASP.NET 5 + Angular, and wanted to use it.

**Comment by tpeczek** [comment]
In which part of functionality are you interested?

**Comment by jlusarreta** [comment]
very Interested in jqgrid

*Javier Lusarreta Ayestarán*
Tlfn:670 733 824
C/Komporte 20A Bajo,
48992 Getxo, Bizkaia.
<http://enorbita.com>

2016-02-23 12:33 GMT+01:00 Tomasz Pęczek <notifications@github.com>:

**Comment by tpeczek** [comment]
Always the one which requires the most of work :D. I'll try to clean up what I have so far during the weekend and start the repo - we can discuss what to do from there.

**Comment by tpeczek** [comment]
You can now track progress in following repositories:
- https://github.com/tpeczek/Lib.AspNetCore.Mvc.JqGrid
- https://github.com/tpeczek/Demo.AspNetCore.JqGrid

**Comment by tpeczek** [comment]
As Lib.AspNetCore.Mvc.JqGrid v1.0.0 is out (http://www.tpeczek.com/2017/04/releasing-libaspnetcoremvcjqgrid-v100.html) I'm closing the issue.
